import type { Discipline, Series, SeriesId } from "./types";

export const disciplines: { id: Discipline; label: string; blurb: string }[] = [
  { id: "finance", label: "Finance", blurb: "Valuation, modelling and company research" },
  { id: "transactions", label: "Transactions", blurb: "IPOs, M&A and restructuring" },
  { id: "research", label: "Research", blurb: "Sector, company and news intelligence" },
  { id: "strategy", label: "Strategy", blurb: "Business models and brand strategy" },
  { id: "macro", label: "Macro", blurb: "Economies, markets and policy" },
  { id: "legal", label: "Legal", blurb: "Judgments, insolvency and regulation" },
  { id: "genai", label: "GenAI", blurb: "Pipelines that produce the work" },
];

/** Ordered as the analytical "thread": company → transaction → market → law → brand. */
export const series: Series[] = [
  {
    id: "equityResearch",
    name: "Equity Research & Models",
    mastheadStyle: "plain",
    kind: "Company research",
    description:
      "Full equity research reports paired with linked 3-statement models, DCF and trading comparables.",
    format: "report",
    countLabel: "6+ companies",
    disciplines: ["finance", "research"],
    identity: "mono",
    method: "11-page report + 8-tab Excel model",
  },
  {
    id: "ipoNotes",
    name: "IPO Notes",
    mastheadStyle: "caps",
    kind: "Listing research",
    description: "One-page IPO notes: issue structure, financials, rationale, risks and broker outlook.",
    format: "onepager",
    countLabel: "25+ issues",
    disciplines: ["finance", "research", "transactions"],
    identity: "burgundy",
    method: "Landscape one-pager",
  },
  {
    id: "ubisBank",
    name: "Ubi's Bank",
    mastheadStyle: "bank",
    kind: "Simulated pitchbooks",
    description:
      "Investment-banking discussion materials for a fictitious advisory brand — sell-side, buy-side and IPO mandates on real companies.",
    format: "deck",
    countLabel: "40+ builds, 20 countries",
    disciplines: ["transactions", "finance"],
    identity: "navy",
    method: "Fixed 22-page structure with a QA suite",
  },
  {
    id: "dealogue",
    name: "Dealogue",
    mastheadStyle: "serif",
    kind: "M&A deal intelligence",
    description: "One-page deal breakdowns: terms, valuation, rationale, financing, regulatory path.",
    format: "onepager",
    disciplines: ["transactions", "research"],
    identity: "burgundy",
    method: "Portrait one-pager",
  },
  {
    id: "workoutWire",
    name: "The Workout Wire",
    mastheadStyle: "caps",
    kind: "Restructuring case tracker",
    description:
      "Distressed situations tracked through filing, creditor structure, legal disputes and recovery outlook.",
    format: "onepager",
    countLabel: "14 cases",
    disciplines: ["transactions", "legal"],
    identity: "burgundy",
    method: "Portrait case tracker",
  },
  {
    id: "sectorscope",
    name: "SECTORSCOPE",
    mastheadStyle: "caps",
    kind: "Sector primers",
    description:
      "PESTLE, Five Forces, value chain, market sizing, SWOT, life cycle and scenarios — on one page.",
    format: "onepager",
    disciplines: ["research", "strategy"],
    identity: "burgundy",
    method: "Framework-led one-pager",
  },
  {
    id: "ecospective",
    name: "Ecospective",
    mastheadStyle: "serif",
    kind: "Economy snapshots",
    description: "Monthly country snapshots: growth, inflation, jobs, markets, rates, trade and policy.",
    format: "onepager",
    countLabel: "14 country editions",
    disciplines: ["macro"],
    identity: "burgundy",
    method: "One-page infographic",
  },
  {
    id: "ledgerline",
    name: "The Ledgerline",
    mastheadStyle: "news",
    kind: "Weekly business paper",
    description: "A week-in-review front page: markets, policy, corporate, banking, world and opinion.",
    format: "newspaper",
    countLabel: "6 weekly editions",
    disciplines: ["macro", "research"],
    identity: "newsprint",
    method: "Single-page e-paper",
  },
  {
    id: "newsAnalysis",
    name: "News Analysis",
    mastheadStyle: "plain",
    kind: "Story explainers",
    description: "One major business story unpacked: summary, implications, stakeholders, glossary, timeline.",
    format: "onepager",
    countLabel: "14 stories, 9 geographies",
    disciplines: ["research"],
    identity: "burgundy",
    method: "Portrait one-pager",
  },
  {
    id: "bmc",
    name: "Business Model Canvas",
    mastheadStyle: "plain",
    kind: "Business models",
    description: "Nine-block canvases for global companies, filled with specific, sourced detail.",
    format: "onepager",
    countLabel: "25+ companies",
    disciplines: ["strategy"],
    identity: "burgundy",
    method: "Landscape canvas",
  },
  {
    id: "caseStudies",
    name: "Brand Case Studies",
    mastheadStyle: "spaced",
    kind: "Brand strategy",
    description: "Origin, challenge, strategy, execution and results — one brand, one page.",
    format: "onepager",
    countLabel: "11 brands, 11 industries",
    disciplines: ["strategy"],
    identity: "burgundy",
    method: "Portrait one-pager",
  },
  {
    id: "judgmentMemos",
    name: "Judgment Memos",
    mastheadStyle: "serif",
    kind: "Legal analysis",
    description:
      "Arbitration judgments distilled into facts, ratio, conclusion, definitions and a memory aid.",
    format: "memo",
    countLabel: "14 cases, 14 jurisdictions",
    disciplines: ["legal"],
    identity: "burgundy",
    method: "Two-page memo",
  },
];

export const seriesById = Object.fromEntries(series.map((s) => [s.id, s])) as Record<SeriesId, Series>;

export const seriesSlug = (id: SeriesId) =>
  id.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

export const seriesFromSlug = (slug: string) => series.find((s) => seriesSlug(s.id) === slug);
